-- Legacy standalone schema moved to supabase/legacy/standalone.sql.
-- Apply supabase/migrations in order to the shared Vibe Check project.
-- Do not run the legacy schema there: its profiles table belongs to Vibe Check.
